In [39]:
import pandas as pd
#loading the data
df=pd.read_csv("/kaggle/input/datasets/obaidhere/netflix-content-strategy-genre-and-rating-analysis/netflix_titles.csv")
##checkng skeleton structure of the  data
df.info

<bound method DataFrame.info of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>

In [40]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [41]:
##since head might be biased checking five rows randomly
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4658,s4659,TV Show,Stretch Armstrong & the Flex Fighters,NaN,"Scott Menville, Steven Yeun, Ogie Banks, Wil W...",United States,"September 7, 2018",2018,TV-Y7,2 Seasons,Kids' TV,Jake Armstrong and his best friends are unexpe...
5111,s5112,TV Show,Myths & Monsters,Daniel Kontur,Nicholas Day,United Kingdom,"December 23, 2017",2017,TV-PG,1 Season,"British TV Shows, Docuseries",This documentary series takes us to the mythic...
1000,s1001,Movie,Wild Dog,Ahishor Solomon,"Nagarjuna Akkineni, Dia Mirza, Saiyami Kher, A...",NaN,"April 22, 2021",2020,TV-MA,126 min,"Action & Adventure, International Movies",A brash but brilliant Indian intelligence agen...
1183,s1184,Movie,Reframe THEATER EXPERIENCE with you,Taketoshi Sado,Perfume,NaN,"March 19, 2021",2020,TV-G,84 min,"International Movies, Music & Musicals","Perfume's Reframe 2019 concert, performed to g..."
6698,s6699,Movie,Enemy,Denis Villeneuve,"Jake Gyllenhaal, Mélanie Laurent, Sarah Gadon,...","Canada, Spain, France","July 15, 2018",2013,R,91 min,"Independent Movies, Thrillers",When a humdrum academic spots his double in a ...

In [42]:
df.shape

(8807, 12)

In [43]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [44]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

# ANALYSIS  ABOUT THE DATA TYPES IN NETFLIX

### . The "Hidden Number" Problems
#### duration: Even though it's an object, it contains numbers (e.g., "90 min" or "1 Season"). You can't calculate the average movie length until you strip the text and convert it to an integer.

#### date_added: This is a string right now (e.g., "September 24, 2021"). To find out if Netflix added more movies in the summer vs. winter, you'll eventually want to convert this to a datetime object.

In [45]:
## checking missing values
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

## Analysis about missing values

#### Director column has a lot of missing values like 30% of the data is missing ,,we are unlikely to use this for the prediction model it will be hectic ,,,the action one can take is do away with the column if it is not very important or fill the null values with nan

#### Cast and Country ,this values are close ,,,this might mean that if a show is missing a country it is also missing a country,,the action i will take here is to prove if they are related.


#### About the date_added it is aclean column what i can do here is do away with the columns with the missing values rather than the whole column,,

### CHECKING IF THE MISSING DIRECTORS ARE DOR TV SHOWS OR MOVIES

In [46]:
# 'isnull()' finds the holes, then we look at the 'type' column for those holes
missing_directors_type = df[df['director'].isnull()]['type'].value_counts()

print("Types of content with missing Directors:")
print(missing_directors_type)

Types of content with missing Directors:
type
TV Show    2446
Movie       188
Name: count, dtype: int64

#### Tv show has the most missing directors,coz of the many directors per epsiode ,,therefore not a data quality issue more of a structural problem as it is almost normal

### CHECKING IF MISSING CAST ARE CONNECTED TO COUNTRY

In [47]:
# Check missing 'cast'
print("Types with missing Cast:")
print(df[df['cast'].isnull()]['type'].value_counts())

# Check missing 'country'
print("\nTypes with missing Country:")
print(df[df['country'].isnull()]['type'].value_counts())

Types with missing Cast:
type
Movie      475
TV Show    350
Name: count, dtype: int64

Types with missing Country:
type
Movie      440
TV Show    391
Name: count, dtype: int64

In [48]:
# How many rows are missing BOTH cast and country?
both_missing = df[df['cast'].isnull() & df['country'].isnull()].shape[0]
print(f"Total rows missing both Cast and Country: {both_missing}")

Total rows missing both Cast and Country: 154

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [51]:
df['type'].unique()

array(['Movie', 'TV Show'], dtype=object)

## DATA CLEANING

### First i create a copy of the file so if i mess it does not affect the main file

In [52]:
netflix_copy=df.copy()
print("Copy of the file has been created")

Copy of the file has been created

In [53]:
# Confirming it worked
print("Netflix Copy created!")
print(f"Original rows: {df.shape[0]}")
print(f"Copy rows: {netflix_copy.shape[0]}")

Netflix Copy created!
Original rows: 8807
Copy rows: 8807

In [54]:
##filling the missing values in director instead of removing the 2000 plus rows
df['director']=df['director'].fillna('Unkown')

In [55]:

netflix_copy['director'] = netflix_copy['director'].fillna('Unknown')
netflix_copy['cast'] = netflix_copy['cast'].fillna('Unknown cast')
netflix_copy['country'] = netflix_copy['country'].fillna('Unknown country')

In [56]:
netflix_copy.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [57]:
##droping rows missing values
netflix_copy.dropna(subset=['rating', 'duration', 'date_added'], inplace=True)

In [58]:
netflix_copy.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [59]:
netflix_copy.shape

(8790, 12)

to solve the durat

In [60]:
# Create a column that just has the number
netflix_copy['duration_num'] = netflix_copy['duration'].str.split(' ').str[0].astype(int)

# Create a column that tells us the unit (min or Season)
netflix_copy['duration_unit'] = netflix_copy['duration'].str.split(' ').str[1]

In [61]:
print("--- Cleaning Complete ---")
print(f"Original Dataset Rows: {df.shape[0]}")
print(f"Cleaned Copy Rows: {netflix_copy.shape[0]}")
print(f"Rows removed (the tiny errors): {df.shape[0] - netflix_copy.shape[0]}")
print("\nMissing Values in netflix_copy:")
print(netflix_copy.isnull().sum())

--- Cleaning Complete ---
Original Dataset Rows: 8807
Cleaned Copy Rows: 8790
Rows removed (the tiny errors): 17

Missing Values in netflix_copy:
show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added       0
release_year     0
rating           0
duration         0
listed_in        0
description      0
duration_num     0
duration_unit    0
dtype: int64

In [62]:
# Selecting all columns with objects
text_columns = netflix_copy.select_dtypes(include=['object']).columns

# Looping through them and removing text spaces
for col in text_columns:
    netflix_copy[col] = netflix_copy[col].str.strip()

print("Hidden spaces removed from all text columns!")

Hidden spaces removed from all text columns!

In [63]:
 dropping useless columns
columns_to_drop = ['show_id'] 
netflix_copy.drop(columns=columns_to_drop, inplace=True)

SyntaxError: invalid syntax (1982535407.py, line 1)

In [ ]:
netflix_copy.columns